[pytest]
norecursedirs = __pycache__ .pytest_cache pytest-cache-files-*
filterwarnings =
    error
    ignore:Very close tone vectors:UserWarning
    ignore:Duplicate tone vectors:UserWarning
    ignore:could not create cache path.*:pytest.PytestCacheWarning
