[pytest]
addopts = -p no:cacheprovider
norecursedirs = __pycache__ .pytest_cache pytest-cache-files-* .tmp
filterwarnings =
    error
    ignore:Very close tone vectors:UserWarning
    ignore:Duplicate tone vectors:UserWarning
